### ISSUE TITLE
inline svgs not working properly in safari! @thomasjbradley

### ISSUE THREAD

**Issue by thatkidmadrid** [thatkidmadrid/offthedome#1]
@thomasjbradley So I built this interface for picking colours for hat panels in the home.html of this repo while troubleshooting in chrome and firefox assuming that autoprefixer would fix any problems that might arise in safari. I'm getting to where I want my picker to work— with fills in the svg paths using javascript— but to my surprise I find out that it breaks in safari because it doesn't fully support inline svg—which is what I need(I think) because jquery can't get into the css of the svg paths... I don't really know what to do or even what stuff to put in this issue because it involves a lot of stuff, but if  you have time to take a look at what I put together or have a suggestion for an alternative way to approach this I'd really appreciate it! Also, I'm fairly certain that my stuff is not very efficient & I tried my best to organize my html css and js.

**Comment by thomasjbradley** [comment]
Okay, so that was an impressively difficult bug. The problem is that jQuery doesn’t work in the SVG namespace, neither does Mustache—they’re only capable of manipulating HTML elements.

So, we have to work around that by using the Javascript DOM directly, creating our own SVG elements and embedding them on the page, without Mustache & without jQuery.

Here’s the JS code solution I’ve come up with:

``` js
// Find the <def> tag for the solid fills
var solidFills = document.querySelector('.solid-fills');

// Loop over all the solid fills from the `swatch-data.js` file
solids.solids.forEach(function (elem, index) {
  // Create a new SVG `pattern` element
  var pattern = document.createElementNS('http://www.w3.org/2000/svg', 'pattern');
  // Populate its attributes with the correct information
  pattern.setAttribute('id', elem.swatchId);
  pattern.setAttribute('patternUnits', 'userSpaceOnUse');
  pattern.setAttribute('width', 125);
  pattern.setAttribute('height', 125);

  // Create a new SVG `image` element
  var image = document.createElementNS('http://www.w3.org/2000/svg', 'image');
  // Populate its attributes with the correct information
  image.setAttributeNS('http://www.w3.org/1999/xlink', 'href', 'img/' + elem.swatchId + '.jpg');
  image.setAttribute('width', 125);
  image.setAttribute('height', 125);

  // Add the <image> tag into the <pattern> tag
  pattern.appendChild(image);
  // Add the <pattern> tag into the <defs> tag
  solidFills.appendChild(pattern);
});
```

So the above code would go in the `swatch-template.js` file, replacing this Mustache + jQuery code:

``` js
var solidFillTemplate = $('#solid-fill-template').html();
Mustache.parse(solidFillTemplate);
var solidFillRendered = Mustache.render(solidFillTemplate, solids);
$('.solid-fills').html(solidFillRendered);
```

And, then you can also delete the `<script>` template tags that generate the patterns from your HTML file.

_This solution only applies to the `<pattern>` SVG generation, you can still keep Mustache & jQuery for the clicky-buttons on the right and everything else._

**Comment by thatkidmadrid** [comment]
thanks @thomasjbradley you're the best!
